# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='user',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nuser.proto\x12\x04user\"\'\n\nUserEntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"3\n\x10UserIndexRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"M\n\x11UserIndexResponse\x12\x0b\n\x03\x65rr\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x10.user.UserEntity\"\x1e\n\x0fUserViewRequest\x12\x0b\n\x03uid\x18\x01 \x01(\x05\"L\n\x10UserViewResponse\x12\x0b\n\x03\x65rr\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x10.user.UserEntity\">\n\x0fUserPostRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\",\n\x10UserPostResponse\x12\x0b\n\x03\x65rr\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\" \n\x11UserDeleteRequest\x12\x0b\n\x03uid\x18\x01 \x01(\x05\".\n\x12UserDeleteResponse\x12\x0b\n\x03\x65rr\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2\x83\x02\n\x04User\x12>\n\tUserIndex\x12\x16.user.UserIndexRequest\x1a\x17.user.UserIndexResponse\"\x00\x12;\n\x08UserView\x12\x15.user.UserViewRequest\x1a\x16.user.UserViewResponse\"\x00\x12;\n\x08UserPost\x12\x15.user.UserPostRequest\x1a\x16.user.UserPostResponse\"\x00\x12\x41\n\nUserDelete\x12\x17.user.UserDeleteRequest\x1a\x18.user.UserDeleteResponse\"\x00\x62\x06proto3'
)




_USERENTITY = _descriptor.Descriptor(
  name='UserEntity',
  full_name='user.UserEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='user.UserEntity.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='user.UserEntity.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=59,
)


_USERINDEXREQUEST = _descriptor.Descriptor(
  name='UserIndexRequest',
  full_name='user.UserIndexRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='user.UserIndexRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='user.UserIndexRequest.page_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=112,
)


_USERINDEXRESPONSE = _descriptor.Descriptor(
  name='UserIndexResponse',
  full_name='user.UserIndexResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='user.UserIndexResponse.err', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='user.UserIndexResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='user.UserIndexResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=191,
)


_USERVIEWREQUEST = _descriptor.Descriptor(
  name='UserViewRequest',
  full_name='user.UserViewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='user.UserViewRequest.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=223,
)


_USERVIEWRESPONSE = _descriptor.Descriptor(
  name='UserViewResponse',
  full_name='user.UserViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='user.UserViewResponse.err', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='user.UserViewResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='user.UserViewResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=301,
)


_USERPOSTREQUEST = _descriptor.Descriptor(
  name='UserPostRequest',
  full_name='user.UserPostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='user.UserPostRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='user.UserPostRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='user.UserPostRequest.age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=365,
)


_USERPOSTRESPONSE = _descriptor.Descriptor(
  name='UserPostResponse',
  full_name='user.UserPostResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='user.UserPostResponse.err', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='user.UserPostResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=411,
)


_USERDELETEREQUEST = _descriptor.Descriptor(
  name='UserDeleteRequest',
  full_name='user.UserDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='user.UserDeleteRequest.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=445,
)


_USERDELETERESPONSE = _descriptor.Descriptor(
  name='UserDeleteResponse',
  full_name='user.UserDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='user.UserDeleteResponse.err', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='user.UserDeleteResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=493,
)

_USERINDEXRESPONSE.fields_by_name['data'].message_type = _USERENTITY
_USERVIEWRESPONSE.fields_by_name['data'].message_type = _USERENTITY
DESCRIPTOR.message_types_by_name['UserEntity'] = _USERENTITY
DESCRIPTOR.message_types_by_name['UserIndexRequest'] = _USERINDEXREQUEST
DESCRIPTOR.message_types_by_name['UserIndexResponse'] = _USERINDEXRESPONSE
DESCRIPTOR.message_types_by_name['UserViewRequest'] = _USERVIEWREQUEST
DESCRIPTOR.message_types_by_name['UserViewResponse'] = _USERVIEWRESPONSE
DESCRIPTOR.message_types_by_name['UserPostRequest'] = _USERPOSTREQUEST
DESCRIPTOR.message_types_by_name['UserPostResponse'] = _USERPOSTRESPONSE
DESCRIPTOR.message_types_by_name['UserDeleteRequest'] = _USERDELETEREQUEST
DESCRIPTOR.message_types_by_name['UserDeleteResponse'] = _USERDELETERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserEntity = _reflection.GeneratedProtocolMessageType('UserEntity', (_message.Message,), {
  'DESCRIPTOR' : _USERENTITY,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserEntity)
  })
_sym_db.RegisterMessage(UserEntity)

UserIndexRequest = _reflection.GeneratedProtocolMessageType('UserIndexRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERINDEXREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserIndexRequest)
  })
_sym_db.RegisterMessage(UserIndexRequest)

UserIndexResponse = _reflection.GeneratedProtocolMessageType('UserIndexResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERINDEXRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserIndexResponse)
  })
_sym_db.RegisterMessage(UserIndexResponse)

UserViewRequest = _reflection.GeneratedProtocolMessageType('UserViewRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERVIEWREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserViewRequest)
  })
_sym_db.RegisterMessage(UserViewRequest)

UserViewResponse = _reflection.GeneratedProtocolMessageType('UserViewResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERVIEWRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserViewResponse)
  })
_sym_db.RegisterMessage(UserViewResponse)

UserPostRequest = _reflection.GeneratedProtocolMessageType('UserPostRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERPOSTREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserPostRequest)
  })
_sym_db.RegisterMessage(UserPostRequest)

UserPostResponse = _reflection.GeneratedProtocolMessageType('UserPostResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERPOSTRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserPostResponse)
  })
_sym_db.RegisterMessage(UserPostResponse)

UserDeleteRequest = _reflection.GeneratedProtocolMessageType('UserDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERDELETEREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserDeleteRequest)
  })
_sym_db.RegisterMessage(UserDeleteRequest)

UserDeleteResponse = _reflection.GeneratedProtocolMessageType('UserDeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERDELETERESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserDeleteResponse)
  })
_sym_db.RegisterMessage(UserDeleteResponse)



_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='user.User',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=496,
  serialized_end=755,
  methods=[
  _descriptor.MethodDescriptor(
    name='UserIndex',
    full_name='user.User.UserIndex',
    index=0,
    containing_service=None,
    input_type=_USERINDEXREQUEST,
    output_type=_USERINDEXRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UserView',
    full_name='user.User.UserView',
    index=1,
    containing_service=None,
    input_type=_USERVIEWREQUEST,
    output_type=_USERVIEWRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UserPost',
    full_name='user.User.UserPost',
    index=2,
    containing_service=None,
    input_type=_USERPOSTREQUEST,
    output_type=_USERPOSTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UserDelete',
    full_name='user.User.UserDelete',
    index=3,
    containing_service=None,
    input_type=_USERDELETEREQUEST,
    output_type=_USERDELETERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
